### ISSUE TITLE
Error Compiling for iOS

### ISSUE THREAD

**Issue by jonathanhollander** [myflashlab/GPS-ANE#10]
I recently updated the GPS ANE for iOS to 2.9.2 from 2.8, but now when I compile I am getting this error:

Error occured while packaging the application:
Compilation failed while executing: Id64

Please help me resolve this issue as this is the only thing keeping me from submitting my app.

**Comment by myflashlab** [comment]
yes, we have posted an exact related topic about this. read here and you'll know how to fix this easily. http://www.myflashlabs.com/urgent-fix-on-our-anes-required-for-air-sdk-v20-or-higher/

**Comment by jonathanhollander** [comment]
I fixed! Though I'll posted how in case others have my same problem.

As I posted above, I actually AM using the new ANE you guys uploaded (2.9.2 with the xcode bug fix mentioned in the link you provided) but I still had this problem. I am on Windows 10 Desktop.

I was actually having this problem with your GPS ANE, as well as the Google Analytics ANE from Milkman games, and the Application/Force Touch ANEs from Distriqt. All 4 of these ANE would throw this error when packaging individually with my application with no other ANEs.

Turns out I was able to resolve it by updating my itunes to the latest version and restart my computer. This solved the problem for this GPS ANE, the Google Analytics ANE from milkman games. Apparently AIR SDK uses the iTunes app's DLLs installed on your computer for installations.... so you need the latest.
