### ISSUE TITLE
Requires 9452000 but found 8489436

### ISSUE THREAD

**Issue by esdebon** [myflashlab/GPS-ANE#16]
When run the app with the ANE (comercial version) get 

`08-31 09:00:42.624 20695-20744/? E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
08-31 09:00:42.641 20695-20744/? W/GooglePlayServicesUtil: Google Play services out of date.  Requires 9452000 but found 8489436`

I am using your last common dependencies

**Comment by esdebon** [comment]
The app work fine after update Google Play Services from Google Play in the device... but I need embed the correct library. A dependency of 40 MB is not an option.

**Comment by myflashlab** [comment]
please explain what 40mb dependency you are referring to?

I'm not sure what the question is now that the google services is updated on the device.

**Comment by esdebon** [comment]
40mb dependency is the Google Play Services APK from Google inc, installing this in the device the problem is fixed.  
But I need the app works without external dependencies.

I am using your last common dependencies
Base, Basemnet and Location

but get :  

> Google Play services out of date. Requires 9452000 but found 8489436

**Comment by myflashlab** [comment]
@esdebon We are keeping the dependencies as updated as possible to be synced with latest Google changes and avoid conflicts with our other ANEs.

The thing is that the Google Play Services APK updates itself automatically and I wonder why you had to update it manually. considering that it updates automatically, there couldn't be any problem with the latest dependencies.

Anyhow, older versions of dependencies are available in the history of our github repository. however, we don't recommend using them.

**Comment by esdebon** [comment]
Ok, I know the risk, in my case, the app is for a company internal use, 4000 tablets with the Google Play access blocked.
