### ISSUE TITLE
bearing = 0

### ISSUE THREAD

**Issue by Fishwok** [myflashlab/GPS-ANE#19]
Hi,

No bearing with my iPad ... it's normal ?
Thanks.

PS: bearing is ok with my noANE test ( "import flash.sensors.Geolocation;").

**Comment by Fishwok** [comment]
Sorry, i post to quickly ... I was mistaken !!
I confused bearing and heading ;(

**Comment by myflashlab** [comment]
no prob :) check this link for more information: https://www.google.com/search?q=what+is+bearing+in+gps&ie=utf-8&oe=utf-8&client=firefox-b-ab
