### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by divlaine** [myflashlab/GPS-ANE#20]
while testing i get some questions:
1. What is the reaction of ANE if gps is not supported or is muted?
2. see only success listeners but can be the situation when I cant get geo coords by Gps.location.getCurrentLocation or Gps.location.start what is the answer?
3. Gps.geocoding.reverse on my coordinates brings an address array with length == 0 (it's empty). For example, with google api I'm getting my adddress by the same coords. May be I have to register some google key for Geocoding?

Sony Z2
airSDK 22

**Comment by myflashlab** [comment]
Here are answers.

1. ```Gps.state.locationServicesEnabled``` is your friend to know if you can use GPS on your device or not.
2. ```Gps.location.getCurrentLocation``` will return null if it's not available. ```Gps.location.start``` will surely return if ```Gps.state.locationServicesEnabled``` is true.
3. haven't experienced that before! could you give more information on this?

**Comment by divlaine** [comment]
device: Sony Z2, os Android 6.0.1
I tried your example coords:
```
public function getAddress():void {
	Gps.init();
	var latitude:Number = -33.7969235;
	var longitude:Number = 150.9224326;
	Gps.geocoding.reverse(latitude, longitude, this_resultHandler);
}

private function this_resultHandler(address:Array):void {
	trace(address);
}
```

Also tried your variation:
public function getAddress():void {
	...
	function this_resultHandler($address:Array):void {
		trace($address);
	}
}

The reslut is the same: address ($address) length == 0.
![2](https://cloud.githubusercontent.com/assets/16689405/21759042/86004bd8-d65a-11e6-9807-a1a685dac5ac.png)

But GET request to Google https://maps.googleapis.com/maps/api/geocode/json returns 9 records in Array:
![1](https://cloud.githubusercontent.com/assets/16689405/21759027/67d0ee24-d65a-11e6-8685-2b0ec0db9425.png)

I thought I made error. But on device Samsung GT-I9192 Galaxy S4 Mini Duos it works:
![3](https://cloud.githubusercontent.com/assets/16689405/21759247/45f6c9a2-d65c-11e6-98e4-708b45fff10e.png)
