### ISSUE TITLE
Permission on iOS with GPS?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/GPS-ANE#21]
What is the correct procedure for using GPS on iOS, regarding permissions with AIR 24?

The PermissionCheck ANE, dosn't support Location for iOS, so do I simply check permission with the GeoLocation Class instead?

Your documentation is not clear on this..

/Martin

**Comment by myflashlab** [comment]
The GPS ANE is taking care of the permission automatically. You don't have to worry about that on the iOS side at all. just use the code as explained and it will be fine. One thing you need to remember is that:

> A new feature for iOS 10 submissions requires you to add the 'purpose string' to your app 
			when accessing a user's private data such as Camera or Photos. For information about providing 
			keys in your app descriptor file, see https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html
To save your time, we have added the required key/values below for your reference:
NOTE: Add them only if you are using that feature in your app.

This has been done on the GPS sample manifest .xml file https://github.com/myflashlab/GPS-ANE/blob/master/FD/application.xml#L65-L73

**Comment by llorenzo** [comment]
Hi, the GPS Localisation is very important in my app. So I want to send the user to the IOS settings screen with the permission ANE. That works fine but how can I find out about the state of the GPS settings. I had hoped the function Gps.state.locationServicesEnabled would return this state. But it is returning true. No matter what the settings really are. Thanks.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
