### ISSUE TITLE
Change the title of GPS popup

### ISSUE THREAD

**Issue by varadig** [myflashlab/GPS-ANE#22]
Hi,

How can I change the title (and maybe the buttons label) on the popup of the gps usage?
And how can I localize the description? For example, My app is working on english and hungarian language and I have to show the popup with different text?

thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
