### ISSUE TITLE
NSLocationAlwaysUsageDescription does not appeared

### ISSUE THREAD

**Issue by varadig** [myflashlab/GPS-ANE#23]
My iOS application is use the location on background, so I need to warning the user, the application is will be always use the location on the background.
But if I setup just the             <key>NSLocationAlwaysUsageDescription</key>
The popup is not appeared.
If i setup all the NSLocation...Description, (            <key>NSLocationUsageDescription</key>
), the message is appeared, but not with the good question.

How can I open the good popup (NsLocationAllwazsUsageDescription) with the good question?

Thanks

**Comment by varadig** [comment]
Here is a sample project:
https://www.dropbox.com/s/yg9dk6wrdumlo65/GPSTest.zip?dl=0

If enable 
```
<key>NSLocationUsageDescription</key>
<string>NSLocationUsageDescription Description</string>

<!--<key>NSLocationWhenInUseUsageDescription</key>-->
<!--<string>NSLocationWhenInUseUsageDescription Description</string>-->

<key>NSLocationAlwaysUsageDescription</key>
<string>NSLocationAlwaysUsageDescription Description</string>
```

the popup is does not appeared. 

But if uncomment the NSLocationWhenInUseUsageDescription, the popup is open, but if I put the applicatoin to the background, the gps stop working.

The appstore is rejceted my application, because i have to use the location service at the background, and I add:

```
<key>UIBackgroundModes</key>
<array>
    <string>location</string>
</array>
```

But the popup NSLocationAlwaysUsageDescription never appeared, and the gps is not working on the background.

Please help me, because this is an ASAP issue of me!

**Comment by varadig** [comment]
The background locationservice is working, but the NSLocationAlwaysUsageDescription popup is'nt show on the app initialization

**Comment by varadig** [comment]
Any news about this issue?

**Comment by varadig** [comment]
???????????????

**Comment by myflashlab** [comment]
Sorry for the delay in our reply. we have been spending busy days while we were moving the office to a new location. So, let's first summarize the problem and then solve it. 

The first thing to notice is that apple is not easily allowing apps to have gps access when they are closed. So, if you have passed that barrier already, then it's good news. please try to upload the sample project again because the above link does not seem to be working. make sure you are not including the licensed ANEs in your files and it would be super helpful if the sample project is a FlashDevelop project so we can easily run locally. I'm on your side now to have this problem fixed/finalized.

**Comment by varadig** [comment]
I can't create FD project, because I work under osx/linux.
Here is a fixed link for the project
https://www.dropbox.com/s/otccq8e12lbkb41/GPSTest.zip?dl=0
The project contains just the source, witout ane's

**Comment by myflashlab** [comment]
Thanks for reporting this. We spent enough time to spot the issue. This is more like a feature enhancement rather than a bug but it's a very important and a handy one. We will be updating the ANE as soon as possible and let you know. This should happen soon. Thanks.

**Comment by varadig** [comment]
Something news about the issue?

**Comment by varadig** [comment]
The Marc 20 update is contain the this buxfix?

**Comment by myflashlab** [comment]
> The Marc 20 update is contain the this buxfix?

No, it doesn't. The latest update of our ANEs included the ANE enhancements with the latest overrideAIR dependency. we will update this ticket as soon as we add the feature.

**Comment by varadig** [comment]
Any update? Of this bug?

**Comment by myflashlab** [comment]
V3.3.0 has this problem fixed. Let us know if you have a problem using it. Read the [changelog here](https://github.com/myflashlab/GPS-ANE#changelog).
