### ISSUE TITLE
I purchased the ANE - permission problecm

### ISSUE THREAD

**Issue by taktitech** [myflashlab/GPS-ANE#25]
Hi,
i use another ane for permissions (distriqt ANE) can i use this ane instead of your PermissionCheck ANE?
i already purchased the other one and build my app around it sorry :(
Thanks

**Comment by myflashlab** [comment]
I'm not sure, you may face dependencies conflicts. We have [provided a way](https://github.com/myflashlab/common-dependencies-ANE#for-ane-developersproviders) for other ANE developers to use our dependencies to avoid possible conflicts. If you are experiencing a problem, your current best option would be to switch to our [PermissionCheck ANE](https://github.com/myflashlab/PermissionCheck-ANE/).

**Comment by taktitech** [comment]
thnx
