### ISSUE TITLE
locationServicesEnabled broken on IOS?

### ISSUE THREAD

**Issue by llorenzo** [myflashlab/GPS-ANE#26]
Hi, the GPS Localisation is very important in my app. So I want to send the user to the IOS settings screen with the permission ANE. That works fine. 
But how can I find out about the state of the GPS settings. I had hoped the function Gps.state.locationServicesEnabled would return this state. But it is returning true. No matter what the settings really are. Thanks.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
