### ISSUE TITLE
geocoding localisation

### ISSUE THREAD

**Issue by 4malik** [myflashlab/GPS-ANE#27]
Hi. 
Couldn't find the possibility to set custom locale for response data in geocoding. 
So how to be if I have more than one language in app, so I  can have a possibility to get an address on different languages. 
For example Google have a param for preferred locale of returned address.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
