### ISSUE TITLE
ios GPS permission error

### ISSUE THREAD

**Issue by 4malik** [myflashlab/GPS-ANE#28]
_exPermissions.check(PermissionCheck.SOURCE_LOCATION) returns 0 (PermissionCheck.PERMISSION_OS_ERR) so cant get what is wrong. on android it works perfect.

air sdk 27
ios 11.2.5
iphone 7 plus

used ANE LAB

**Comment by myflashlab** [comment]
```PermissionCheck.SOURCE_LOCATION``` works on Android ONLY.

on iOS, you must use either of the following:
```
PermissionCheck.SOURCE_LOCATION_ALWAYS
PermissionCheck.SOURCE_LOCATION_WHEN_IN_USE
```

Please make sure you are reading the sample codes more carefuly. Thanks.
https://github.com/myflashlab/PermissionCheck-ANE/blob/master/AIR/src/Main.as#L182-L186

**Comment by 4malik** [comment]
Thx guys. Ill try to read with more attention
