### ISSUE TITLE
There is OK button in demo GPS ane.

### ISSUE THREAD

**Issue by KangPrince** [myflashlab/GPS-ANE#3]
Hi,
After I buy your gps ane, there will not be ok button.
Right?

**Comment by myflashlab** [comment]
Of course the demo button will be removed on the commercial version.

**Comment by KangPrince** [comment]
Hi,
Your web site has something wrong.
I can't enter your site and buy ane.

**Comment by myflashlab** [comment]
It is loading fine, i just checked!

On Saturday, October 3, 2015, Kang Hojun <notifications@github.com> wrote:

> Hi,
> Your web site has something wrong.
> I can't enter your site and buy ane.
>
>
> On Sat, Oct 3, 2015 at 6:20 PM, myflashlab <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Of course the demo button will be removed on the commercial version.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/myflashlab/GPS-ANE/issues/3#issuecomment-145230341>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/3#issuecomment-145270225>.
>


-- 
Sent from iPhone

**Comment by KangPrince** [comment]
I can't enter your website.
After connecting your site, I can't surf your site, but I can download gz file.
Please, check your site one more.

**Comment by myflashlab** [comment]
> ... but I can download gz file.

what is gz file?!

it's really weird that you can't load the site! what do you see if you click this link: http://myappsnippet.com/product/gps-air-extension/

**Comment by KangPrince** [comment]
http://myappsnippet.com/product/gps-air-extension/ is the same.

**Comment by myflashlab** [comment]
there must be something wrong on your side, the page is loading fine here.

**Comment by KangPrince** [comment]
What will I do ?

**Comment by myflashlab** [comment]
maybe try another computer or contact your ISP!

**Comment by KangPrince** [comment]
I tried another computer, but the same.

How can I buy your gps ane - commercial version ?

**Comment by KangPrince** [comment]
Your website is good when I am under login. but in case that I'm not login,
your website has something wrong.
Please, check.

**Comment by myflashlab** [comment]
I think you were right, we had several other reports about the downtime! I think it was a cache problem on the server. would you please check if it's loading fine now?
