### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by heliomarch** [myflashlab/GPS-ANE#30]
On start
 $ distance: Number - here are and meters or miles or kilometers?

**Comment by myflashlab** [comment]
meters.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
