### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by dogofpavlov** [myflashlab/GPS-ANE#4]
So I recently bought your ANE and when I go to download it from logging into my account I get a Expired Message of "Sorry, this download has expired Go to homepage". Please update the URL so I can use the correct ANE.

**Comment by myflashlab** [comment]
To solve this kind of problems, please contact the server guys using the contact form on myappsnippet.com The issues page on GitHub is intended for tech issues on ANEs. Thanks.
