### ISSUE TITLE
Error Compiling for iOS

### ISSUE THREAD

**Issue by jonathanhollander** [myflashlab/GPS-ANE#5]
Hello I just recently bought this GPS-ANE again for another client, and I am having a problem compiling on iOS the latest version 2.9 with the commondependencies 4.0.  

I have used 2.0 for a previous project and had no problem compiling, but with this latest version it doesn't work. Here is the error I see.

I have disabled all other ANE's besides the GPS ANE and the common dependencies but I am still having the problem.

duplicate symbol _OBJC_METACLASS_$_DeviceInfo in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)

duplicate symbol _OBJC_CLASS_$_DeviceInfo in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)

duplicate symbol _getEnumTitle in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _command in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _contextInitializer in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _contextFinalizer in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _OBJC_CLASS_$_Conversions in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)

duplicate symbol _OBJC_METACLASS_$_Conversions in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)

ld: 8 duplicate symbols for architecture arm64

duplicate symbol _OBJC_METACLASS_$_DeviceInfo in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)

duplicate symbol _OBJC_CLASS_$_DeviceInfo in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)

duplicate symbol _getEnumTitle in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _command in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _contextInitializer in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _contextFinalizer in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)

duplicate symbol _OBJC_CLASS_$_Conversions in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)

duplicate symbol _OBJC_METACLASS_$_Conversions in:

    C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)

    C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)

ld: 8 duplicate symbols for architecture armv7

Compilation failed while executing : ld64

**Comment by jonathanhollander** [comment]
turns out I was able to compile for iOS if I didn't include the commonDependenciesV4.0 and it even works. Not sure if that means it's working as intended.

**Comment by myflashlab** [comment]
Please read the last couple of paragraphs here
https://github.com/myflashlab/common-dependencies-ANE/blob/master/README.md
which
we have talked about this exact problem and how to solve it in iOS.

FYI: the commondependency .ane can be moved out on "iOS" and the extension
will work fine because that's actually needed on the Android side only. But
it's safe to keep it anyhow and instead do as the instructions explained in
the above link.

On Thursday, December 3, 2015, jonathanhollander <notifications@github.com>
wrote:

> turns out I was able to compile for iOS if I didn't include the
> commonDependenciesV4.0 and it even works. Not sure if that means it's
> working as intended.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/5#issuecomment-161434894>.
>


-- 
Sent from iPhone

**Comment by myflashlab** [comment]
As a general rule, when using more than one ANE in your ios apps, you must
turn on the "hideAneLibSymbols" feature. To make sure nothing would get
conflicted.

On Wednesday, December 2, 2015, jonathanhollander <notifications@github.com>
wrote:

> Hello I just recently bought this GPS-ANE again for another client, and I
> am having a problem compiling on iOS the latest version 2.9 with the
> commondependencies 4.0.
>
> I have used 2.0 for a previous project and had no problem compiling, but
> with this latest version it doesn't work. Here is the error I see.
>
> I have disabled all other ANE's besides the GPS ANE and the common
> dependencies but I am still having the problem.
>
> duplicate symbol *OBJC_METACLASS*$_DeviceInfo in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)
>
> duplicate symbol *OBJC_CLASS*$_DeviceInfo in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)
>
> duplicate symbol _getEnumTitle in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol _command in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol _contextInitializer in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol _contextFinalizer in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol *OBJC_CLASS*$_Conversions in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)
>
> duplicate symbol *OBJC_METACLASS*$_Conversions in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)
>
> ld: 8 duplicate symbols for architecture arm64
>
> duplicate symbol *OBJC_METACLASS*$_DeviceInfo in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)
>
> duplicate symbol *OBJC_CLASS*$_DeviceInfo in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(DeviceInfo.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(DeviceInfo.o)
>
> duplicate symbol _getEnumTitle in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol _command in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol _contextInitializer in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol _contextFinalizer in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(exGps.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(ExDependency.o)
>
> duplicate symbol *OBJC_CLASS*$_Conversions in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)
>
> duplicate symbol *OBJC_METACLASS*$_Conversions in:
>
> C:\Users\Ryan\AppData\Local\Temp\bc5c4625-ef5f-4eb4-900b-b1e73011ca16/libcom.myflashlab.air.extensions.gps.a(Conversions.o)
>
> C:\Users\Ryan\AppData\Local\Temp\e18cd868-3094-42e5-9fa0-76c2f98b004e/libcom.doitflash.air.extensions.dependency.a(Conversions.o)
>
> ld: 8 duplicate symbols for architecture armv7
>
> Compilation failed while executing : ld64
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/5>.
>


-- 
Sent from iPhone
