### ISSUE TITLE
Gps.isSupported

### ISSUE THREAD

**Issue by jonathanhollander** [myflashlab/GPS-ANE#6]
Not sure if this is the place to post it, but how do we check if the ANE is supported on the Device? There is no standard ANE property like ".isSupported".

If I put Gps.location.getCurrentLocation and they have location services disabled, what happens? 

I've been trying to leech off of the AIR provided Geolocation.isSupported, but it seems the conditions for it's support and the ANE are not the same.

**Comment by myflashlab** [comment]
All devices have gps and even if it's off, the extension will automatically ask
user to turn it on.

On Friday, December 4, 2015, jonathanhollander <notifications@github.com>
wrote:

> Not sure if this is the place to post it, but how do we check if the ANE
> is supported on the Device? There is no standard ANE property like
> ".isSupported".
>
> If I put Gps.location.getCurrentLocation and they have location services
> disabled, what happens?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/6>.
>


-- 
Sent from iPhone

**Comment by jonathanhollander** [comment]
Thanks for the fast reply, if the user denies the request will the complete handler just return a null location?

**Comment by myflashlab** [comment]
I think you should check the gps state first if you want to make sure if
user has the gps enabled or not. Please check the sample files and you'll
see a properly like checkState or something like that.

On Friday, December 4, 2015, jonathanhollander <notifications@github.com>
wrote:

> Thanks for the fast reply, if the user denies the request will the
> complete handler just return a null location?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/6#issuecomment-161799013>.
>


-- 
Sent from iPhone

**Comment by myflashlab** [comment]
Try: Gps.state.locationServicesEnabled

On Friday, December 4, 2015, jonathanhollander <notifications@github.com>
wrote:

> Not sure if this is the place to post it, but how do we check if the ANE
> is supported on the Device? There is no standard ANE property like
> ".isSupported".
>
> If I put Gps.location.getCurrentLocation and they have location services
> disabled, what happens?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/6>.
>


-- 
Sent from iPhone

**Comment by jonathanhollander** [comment]
Thanks again, though im not necessarily sure how to use it to solve my problem.

Am I to check the Gps.state.locationServicesEnabled in the complete handler of the Gps.location.getCurrentLocation? is that the intent? will the complete handler passed to the getCurrentLocation fire no matter what?

**Comment by jonathanhollander** [comment]
if the Gps.state.locationServicesEnabled ever returned false, I would simply ignore and run the Gps.location.getCurrentLocation to begin the request from the user to allow it... so I guess I don't get its purpose. Why bother to check before the the request if the request will turn it on anyway?

**Comment by myflashlab** [comment]
You can use ```Gps.state.locationServicesEnabled``` to check if gps is enabled or not. if it's not you can ask user to turn it on with a popup or something in your app and when they hit "ok" in your app popup, you can call ```Gps.location.getCurrentLocation``` 

That's just an idea! do whatever else pleases you though :)

**Comment by jonathanhollander** [comment]
ahh ok I understand now. Thank you for your help!
