### ISSUE TITLE
GPS Location Time property

### ISSUE THREAD

**Issue by tomcharyga** [myflashlab/GPS-ANE#7]
We need to be able to read the time stamp from the GPS sensor (independent of the system clock).
We tried the demo but it looks like the time retrieved by the extension is the device system time.
Is it possible to get system independent time stamp in your extension from the GPS sensor?
Thank you in advance

**Comment by myflashlab** [comment]
We are returning the timestamp provided by the native APIs. anything they provide is what we return through the extension. GPS timestamp value tested on different devices is very different from one device to another and I think that is related to the actual physical gps chipset that factories are building. you can search for this information on Android or iOS forums but as far as we know, although the gps timestamp must be independent from the device's time, in practice, it doesn't seem to behave that way.
