### ISSUE TITLE
UNEXPECTED TOP-LEVEL ERROR

### ISSUE THREAD

**Issue by varadig** [myflashlab/GPS-ANE#8]
I got this error, when i trie to compie to Android
http://postimg.org/image/8h0vffbw7/

I use IntelliJ IDEA and I changed to vmoption to 

-Xms6g
-Xmx6g
-XX:MaxPermSize=350m
-XX:ReservedCodeCacheSize=225m
-XX:+UseCompressedOops

**Comment by myflashlab** [comment]
We don't use IntelliJ IDE but maybe this link would help you http://stackoverflow.com/questions/25013638/android-studio-google-jar-causing-gc-overhead-limit-exceeded-error

**Comment by varadig** [comment]
Ok I solve this issue, with jvm.config with this line:
`java.args=-Xmx2048m -Xms1024m -Dsun.io.useCanonCaches=false`
